name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build index.html
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          pandoc -f markdown -t html5 -s --template easy_template.html --metadata title="Sotetsu Suzugamine" --variable=title="" index.md > index.html
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Build index.html
